[package]
name = "prov-cosmwasm-schema"
version = "1.0.0-provbeta2"
authors = ["Fred Kneeland <fkneeland@figure.com>"]
edition = "2018"
description = "A dev-dependency for CosmWasm contracts to generate JSON Schema files."
repository = "https://github.com/provenance-io/cosmwasm/tree/main/packages/schema"
license = "Apache-2.0"

[dependencies]
schemars = "0.8.1"
serde_json = "1.0"
